#!/bin/bash
# scripts/get_video_metadata.sh

set -e

JSON_FILE=$(ls -t output/*.json 2>/dev/null | head -1)

if [ -z "$JSON_FILE" ] || [ ! -f "$JSON_FILE" ]; then
  echo "Warning: No JSON metadata file found. Using generic title."
  TITLE="Auto-Generated Beat - $(date +%Y-%m-%d)"
  DESCRIPTION="A new beat generated by the Rust Beats project.

This track is 100% royalty-free (CC0) for use in your streams, videos, and projects.

#rust #generativemusic #autobeat #royaltyfreemusic"

else
  echo "Reading metadata from $JSON_FILE"
  
  # Read metadata using jq
  NAME=$(jq -r '.name // ""' "$JSON_FILE")
  GENRE_ARRAY=$(jq -r '.genre | @json' "$JSON_FILE")
  BPM=$(jq -r '.tempo // 0' "$JSON_FILE")  # Note: JSON uses 'tempo' not 'bpm'
  
  # Create Title
  if [ -n "$NAME" ] && [ "$NAME" != "null" ]; then
    TITLE="$NAME | Royalty-Free Generative Music"
  else
    TITLE="Auto-Generated Beat - $(date +%Y-%m-%d)"
  fi
  
  # Create Description
  DESCRIPTION_BODY="A new beat generated by the Rust Beats project!
Song: $NAME
"
  
  if [ "$GENRE_ARRAY" != "null" ] && [ "$GENRE_ARRAY" != "[]" ]; then
    GENRES=$(jq -r '.genre | join(", ")' "$JSON_FILE")
    DESCRIPTION_BODY="$DESCRIPTION_BODY
Genre: $GENRES"
  fi
  
  # Check if BPM is valid (handle float values)
  if [ -n "$BPM" ] && [ "$BPM" != "null" ] && [ "$BPM" != "0" ]; then
    BPM_INT=$(echo "$BPM" | cut -d. -f1)
    if [ "$BPM_INT" -gt 0 ] 2>/dev/null; then
      DESCRIPTION_BODY="$DESCRIPTION_BODY
BPM: ${BPM_INT}"
    fi
  fi
  
  DESCRIPTION="$DESCRIPTION_BODY

✅ 100% Free to Use!
All music is free for content creators, YouTubers, streamers, and podcasters. No attribution required (but appreciated). License: CC0 Public Domain.

#rust #generativemusic #royaltyfreemusic #instrumental #autobeat"
fi

# This is for GitHub Actions to read the output
# Note the special syntax for multiline strings
if [ -n "$GITHUB_OUTPUT" ]; then
  echo "title=$TITLE" >> "$GITHUB_OUTPUT"
  {
    echo "description<<EOF"
    echo "$DESCRIPTION"
    echo "EOF"
  } >> "$GITHUB_OUTPUT"
fi

echo "--- Metadata for YouTube ---"
echo "Title: $TITLE"
echo "Description: $DESCRIPTION"
echo "------------------------------"