import os
import json
import glob
from datetime import datetime
import google.oauth2.credentials
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload

# Load .env file if it exists (for local development)
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    # python-dotenv not installed, skip loading .env file
    pass

OUTPUT_DIR = "output"

def find_latest_json():
    """Find the most recent JSON metadata file."""
    json_files = glob.glob(f"{OUTPUT_DIR}/*.json")
    if not json_files:
        return None
    # Sort by modification time, most recent first
    json_files.sort(key=os.path.getmtime, reverse=True)
    return json_files[0]


def load_metadata(json_file):
    """Load metadata from JSON file."""
    try:
        with open(json_file, 'r') as f:
            return json.load(f)
    except (FileNotFoundError, json.JSONDecodeError) as e:
        print(f"Warning: Error reading metadata file: {e}")
        return None


def get_video_metadata():
    """Get video title and description from JSON metadata or environment variables."""
    # First, try to get from environment (for GitHub Actions compatibility)
    title = os.environ.get("VIDEO_TITLE")
    description = os.environ.get("VIDEO_DESCRIPTION")
    
    if title and description:
        return title, description
    
    # If not in environment, try to read from JSON file
    json_file = find_latest_json()
    
    if json_file and os.path.exists(json_file):
        print(f"Reading metadata from {json_file}")
        metadata = load_metadata(json_file)
        
        if metadata:
            # Format title
            name = metadata.get("name", "")
            if name and name != "null":
                title = f"{name} | Royalty-Free Generative Music"
            else:
                today = datetime.now().strftime("%Y-%m-%d")
                title = f"Auto-Generated Beat - {today}"
            
            # Format description
            genre = metadata.get("genre", [])
            tempo = metadata.get("tempo", 0)
            
            description_parts = ["A new beat generated by the Rust Beats project!"]
            
            if name:
                description_parts.append(f"Song: {name}")
            
            if genre and isinstance(genre, list) and len(genre) > 0:
                genre_str = ", ".join(genre)
                description_parts.append(f"\nGenre: {genre_str}")
            
            if tempo and tempo > 0:
                bpm_int = int(tempo)
                description_parts.append(f"BPM: {bpm_int}")
            
            description_parts.append("""
✅ 100% Free to Use!
All music is free for content creators, YouTubers, streamers, and podcasters. No attribution required (but appreciated). License: CC0 Public Domain.

🔗 Links:
• GitHub Repository: https://github.com/petarzarkov/rust-beats
• Listen & Download: https://petarzarkov.github.io/rust-beats/
• YouTube Channel: https://www.youtube.com/@RustBeats

#rust #generativemusic #royaltyfreemusic #instrumental #autobeat""")
            
            description = "\n".join(description_parts)
            return title, description
    
    # Fallback to default
    print("Warning: No metadata found, using defaults")
    today = datetime.now().strftime("%Y-%m-%d")
    title = f"Auto-Generated Beat - {today}"
    description = """A new beat generated by the Rust Beats project.

This track is 100% royalty-free (CC0) for use in your streams, videos, and projects.

🔗 Links:
• GitHub Repository: https://github.com/petarzarkov/rust-beats
• Listen & Download: https://petarzarkov.github.io/rust-beats/
• YouTube Channel: https://www.youtube.com/@RustBeats

#rust #generativemusic #autobeat #royaltyfreemusic"""
    
    return title, description


def upload_video():
    # 1. Setup Credentials from GitHub Secrets (Environment Variables)
    client_id = os.environ.get("YOUTUBE_CLIENT_ID")
    client_secret = os.environ.get("YOUTUBE_CLIENT_SECRET")
    refresh_token = os.environ.get("YOUTUBE_REFRESH_TOKEN")
    
    if not all([client_id, client_secret, refresh_token]):
        raise ValueError("Missing YOUTUBE_ credentials in environment variables.")

    # Construct the credentials object manually using the refresh token
    creds = google.oauth2.credentials.Credentials(
        None, # No access token yet, will refresh
        refresh_token=refresh_token,
        token_uri="https://oauth2.googleapis.com/token",
        client_id=client_id,
        client_secret=client_secret
    )

    # 2. Create YouTube Service
    youtube = build("youtube", "v3", credentials=creds)

    # 3. Get Metadata (from JSON file or environment)
    title, description = get_video_metadata()
    file_path = "output/youtube_video.mp4"

    print(f"Uploading: {title}")

    # 4. Prepare Upload
    body = {
        "snippet": {
            "title": title[:100], # YouTube max title length
            "description": description,
            "tags": ["rust", "generative music", "beats", "royalty free"],
            "categoryId": "10" # Music
        },
        "status": {
            "privacyStatus": "public", # or "private", "unlisted"
            "selfDeclaredMadeForKids": False
        }
    }

    media = MediaFileUpload(
        file_path, 
        chunksize=-1, 
        resumable=True,
        mimetype="video/mp4"
    )

    # 5. Execute Upload
    request = youtube.videos().insert(
        part="snippet,status",
        body=body,
        media_body=media
    )

    response = None
    while response is None:
        status, response = request.next_chunk()
        if status:
            print(f"Uploaded {int(status.progress() * 100)}%")

    print(f"Upload Complete! Video ID: {response.get('id')}")

if __name__ == "__main__":
    upload_video()